version: '3.8'

services:
  app:
    build: .
    volumes:
      - app_data:/var/www/html
    container_name: ${CONTAINER_NAME_PREFIX}-app
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "
      php artisan migrate --force &&
      php-fpm
      "

  db:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME_PREFIX}-mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: rootadmin
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_data:
